### ISSUE TITLE
Crash: firework rockets on server

### ISSUE THREAD

**Issue by MeeniMc** [gbl/EasierCrafting#34]
I have found the following scenario that crashes the client in a client-server game:

1. MC 1.16.1 fabric.
2. Addon is not installed on the server
3. Option 'additional recipes' is active on the client side addon
4. Open the 4x4 crafting interface with paper and gunpowder in inventory
5. Client crash 
6. Server sees client disconnect, no error server side.

```
[10:56:59] [main/FATAL]: Error executing task on Client
java.lang.UnsupportedOperationException: Not supported yet.
	at de.guntram.mcmod.easiercrafting.InventoryGeneratedRecipe.method_8114(InventoryGeneratedRecipe.java:63) ~[easiercrafting-1.16-fabric0.13.1-1.6.3.jar:?]
	at de.guntram.mcmod.easiercrafting.RecipeTreeSet$1.compare(RecipeTreeSet.java:46) ~[easiercrafting-1.16-fabric0.13.1-1.6.3.jar:?]
	at de.guntram.mcmod.easiercrafting.RecipeTreeSet$1.compare(RecipeTreeSet.java:12) ~[easiercrafting-1.16-fabric0.13.1-1.6.3.jar:?]
	at java.util.TreeMap.compare(TreeMap.java:1564) ~[?:?]
	at java.util.TreeMap.addEntryToEmptyMap(TreeMap.java:768) ~[?:?]
	at java.util.TreeMap.put(TreeMap.java:777) ~[?:?]
	at java.util.TreeMap.put(TreeMap.java:534) ~[?:?]
	at java.util.TreeSet.add(TreeSet.java:255) ~[?:?]
	at de.guntram.mcmod.easiercrafting.RecipeBook.updateRecipes(RecipeBook.java:407) ~[easiercrafting-1.16-fabric0.13.1-1.6.3.jar:?]
	at de.guntram.mcmod.easiercrafting.RecipeBook.afterInitGui(RecipeBook.java:146) ~[easiercrafting-1.16-fabric0.13.1-1.6.3.jar:?]
	at de.guntram.mcmod.easiercrafting.ExtendedGuiCrafting.method_25426(ExtendedGuiCrafting.java:25) ~[easiercrafting-1.16-fabric0.13.1-1.6.3.jar:?]
	at net.minecraft.class_437.method_25423(class_437.java:321) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1507(class_310.java:895) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3929.handler$bgh000$checkCraftScreen(class_3929.java:1053) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3929.method_17541(class_3929.java) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_634.method_17587(class_634.java:1143) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3944.method_17591(class_3944.java:42) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3944.method_11054(class_3944.java:12) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:988) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:654) [intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [intermediary-minecraft-1.16.1-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-loader-0.9.1+build.205.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26) [fabric-loader-0.9.1+build.205.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[10:57:06] [main/FATAL]: Error executing task on Client
```

Interestingly, the same error is not present with the 6x6 crafting table:

4. open the 6x6 crafting table
5 Rockets are not listed as a possible produce
6 Search for rockets (enter)
7 Rocket recipe appears, it has no ingredients listed in the area where ingredients are listed (bottom of craft interface)
8 Clicking this recipe has no effect (no crash)

To other players: if you get stuck with opening the inventory loop-crashing, you can open a chest and remove the gunpowder or paper from your inventory, that will stop the crash loop.

**Comment by gbl** [comment]
You're using an older version (1.6.3) of the mod: easiercrafting-1.16-fabric0.13.1-**1.6.3**.jar

Version 1.6.4 fixes that (or version 1.6.5, which also includes a few more languages, but only works from MC 1.16.2 on).

**Comment by Meeni-mc** [comment]
Yes, I was just checking this. The problem is my server runs 1.16.1 and can't upgrade, and the new version of the mod cannot load on 1.16.1 clients.

**Comment by MeeniMc** [comment]
I really wish Curse would not be so confusing for finding things, would prevent me making a fool of myself.

**Comment by gbl** [comment]
This file is for 1.16 and 1.16.1, and has the bug fixed: https://www.curseforge.com/minecraft/mc-mods/easiercrafting/files/3044855
