### ISSUE TITLE
Crash on right clicking brewing stand [21w11a]

### ISSUE THREAD

**Issue by ghost** [gbl/EasierCrafting#37]
It seems like right clicking brewing stands, furnace, smoker, blast furnace is crashing the game. I pasted a log below for when I clicked the brewing stand.

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 20/03/21 19:20
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.class_465.handler$zfe000$patchTitleWithBurntime(class_465.java:766)
	at net.minecraft.class_465.method_2388(class_465.java)
	at de.guntram.mcmod.easiercrafting.ExtendedGuiBrewingStand.method_2388(ExtendedGuiBrewingStand.java:56)
	at net.minecraft.class_465.method_25394(class_465.java:135)
	at net.minecraft.class_472.method_25394(class_472.java:32)
	at net.minecraft.class_757.method_3192(class_757.java:836)
	at net.minecraft.class_310.method_1523(class_310.java:1073)
	at net.minecraft.class_310.method_1514(class_310.java:700)
	at net.minecraft.client.main.Main.main(Main.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
```

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

```
-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_465.handler$zfe000$patchTitleWithBurntime(class_465.java:766)
	at net.minecraft.class_465.method_2388(class_465.java)
	at de.guntram.mcmod.easiercrafting.ExtendedGuiBrewingStand.method_2388(ExtendedGuiBrewingStand.java:56)
	at net.minecraft.class_465.method_25394(class_465.java:135)
	at net.minecraft.class_472.method_25394(class_472.java:32)

-- Screen render details --
Details:
	Screen name: de.guntram.mcmod.easiercrafting.ExtendedGuiBrewingStand
	Mouse location: Scaled: (480, 256). Absolute: (960.000000, 513.000000)
	Screen size: Scaled: (960, 514). Absolute: (1920, 1027). Scale factor of 2.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['128_GB'/2115, l='ClientLevel', x=3295.38, y=64.00, z=2244.60]]
	Chunk stats: 729, 483
	Level dimension: minecraft:overworld
	Level spawn location: World: (-208,63,-239), Section: (at 0,15,1 in -13,3,-15; chunk contains blocks -208,-64,-240 to -193,319,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 10160864 game time, 10353849 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:364)
	at net.minecraft.class_310.method_1587(class_310.java:2259)
	at net.minecraft.class_310.method_1514(class_310.java:719)
	at net.minecraft.client.main.Main.main(Main.java:216)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- System Details --
Details:
	Minecraft Version: 21w11a
	Minecraft Version ID: 21w11a
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5610997048 bytes (5351 MB) / 6979321856 bytes (6656 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		crowdin-translate: CrowdinTranslate 1.3+1.17-alpha20w49a
		easierchests: EasierChests 21w11a-fabric0.32.4-1.6.3
		easiercrafting: EasierCrafting 21w11a-fabric0.32.4-1.6.7
		fabric: Fabric API 0.32.4+1.17
		fabric-api-base: Fabric API Base 0.2.1+524a2e85bd
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.0+b5106233bd
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.6+03bff30fbd
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+92519afabd
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9d6353abd
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afabd
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+41a68552bd
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+92519afabd
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+92519afabd
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.7+03bff30fbd
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+92519afabd
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+d748de6cbd
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afabd
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+92519afabd
		fabric-item-api-v1: Fabric Item API (v1) 1.2.3+36b77c3ebd
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.4+41a68552bd
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+524a2e85bd
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3ebd
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.3+40e100ebbd
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+92519afabd
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afabd
		fabric-models-v0: Fabric Models (v0) 0.2.1+92519afabd
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+7268309ebd
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+40e100ebbd
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afabd
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.5+40e100ebbd
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+92519afabd
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+92519afabd
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+03bff30fbd
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+92519afabd
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.6+92519afabd
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.1.0+2a1dabb6bd
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+92519afabd
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+92519afabd
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+92519afabd
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.2+41a68552bd
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.4+1eb2670ebd
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+41a68552bd
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.7+41a68552bd
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.7+03bff30fbd
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.3+41a68552bd
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+92519afabd
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.9+36b77c3ebd
		fabricloader: Fabric Loader 0.11.3
		gbfabrictools: GBfabrictools 1.3.4+21w10a
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.17-alpha.21.11.a
		wi_zoom: WI Zoom 1.3-MC21w11a
	Launched Version: fabric-loader-0.11.3-21w11a
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 3.2.0 NVIDIA 461.92, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.2
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/EasierChestIcons.zip (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
```

**Comment by gbl** [comment]
Thanks for that, will look into it.

**Comment by gbl** [comment]
Fixed, please redownload from Modrinth here: https://modrinth.com/mod/easiercrafting/version/pSQCMjNj
I didn't give it a new version number as I consider this a part of the weekly update process, not a genuine bug fix.
