### ISSUE TITLE
Crash on startup when with Anvil Fix and Tax Free Levels

### ISSUE THREAD

**Issue by ChromaPIE** [gbl/EasierCrafting#41]
Log: https://paste.ubuntu.com/p/XvnNY93h3Q/
with a crashlog following: https://paste.ubuntu.com/p/2ZgDTW7SVJ/

**Comment by gbl** [comment]
I'm afraid this is a bug in Mesh and needs to be addressed there:

```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3695.method_15396(String)" because "profiler" is null
	at io.github.glasspane.mesh.impl.crafting.MeshRecipeManager.reloadRecipes(MeshRecipeManager.java:46)
	at net.minecraft.class_1863.handler$bkm000$createMeshRecipes(class_1863.java:1538)
	at net.minecraft.class_1863.method_20705(class_1863.java)
	at de.guntram.mcmod.easiercrafting.LocalRecipeManager.load(LocalRecipeManager.java:52)
```

There's a few recipes I'm loading myself, as they aren't defined as proper Minecraft Shaped Recipes. When I'm doing that, I'm calling the `apply` method (which is `method_20705` in the stack trace), Mesh seems to intercept my call and do its own thing, and crash. Not sure if you're loading Mesh yourself, or if it comes as a dependency of another mod, but it is in your loaded mod list:

```
	Fabric Mods: 
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
```

**Comment by gbl** [comment]
In version 1.7 (just uploaded to Modrinth and CF) this should be fixed, as I'm passing an empty profiler instead of `null` now. MC itself doesn't use the profiler so `null` is fine, but it seems Mesh can't handle that.
