### ISSUE TITLE
1.20.2 crash

### ISSUE THREAD

**Issue by flyingitalianman** [gbl/EasierCrafting#68]
got this when trying to open the inventory while using the current version on 1.20.2:

java.lang.ClassCastException: class net.minecraft.class_8786 cannot be cast to class net.minecraft.class_1860 (net.minecraft.class_8786 and net.minecraft.class_1860 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3bbc39f8)
	at de.guntram.mcmod.easiercrafting.RecipeBook.updateRecipes(RecipeBook.java:379)
	at de.guntram.mcmod.easiercrafting.RecipeBook.afterInitGui(RecipeBook.java:152)
	at de.guntram.mcmod.easiercrafting.ExtendedGuiInventory.method_25426(ExtendedGuiInventory.java:23)
	at net.minecraft.class_437.method_25423(class_437.java:298)
	at net.minecraft.class_310.method_1507(class_310.java:1135)
	at net.minecraft.class_310.handler$zzp000$easiercrafting$displayExtendedInventory(class_310.java:3595)
	at net.minecraft.class_310.method_1508(class_310.java:2058)
	at net.minecraft.class_310.method_1574(class_310.java:1933)
	at net.minecraft.class_310.method_1523(class_310.java:1237)
	at net.minecraft.class_310.method_1514(class_310.java:856)
	at net.minecraft.client.main.Main.main(Main.java:253)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by NakyoykaN** [comment]
Can we get an update?  1.20.4 is also out but it probably won't require any changes from 1.20.3.

**Comment by gbl** [comment]
There is an 1.20.4 version now.
