### ISSUE TITLE
Game crash when trying to open inventory

### ISSUE THREAD

**Issue by somnomania** [gbl/EasierCrafting#71]
Crash log points to this mod as the culprit; log is included. I've removed EC from my loadout for the time being.
[crash-2024-01-13_05.19.13-client.txt](https://github.com/gbl/EasierCrafting/files/13927677/crash-2024-01-13_05.19.13-client.txt)

**Comment by gbl** [comment]
This looks like an incompatibility with EssentialGui, from the stack trace:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
        at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
        at java.base/java.lang.String.charAt(String.java:1517)
        at lordrius.essentialgui.events.ItemTooltip.lambda$registerTooltips$0(ItemTooltip>
        at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(Ite>
        at net.minecraft.class_1799.handler$bdc000$fabric-item-api-v1$getTooltip(class_17>
        at net.minecraft.class_1799.method_7950(class_1799.java:791)
.....
        at net.minecraft.class_7706.method_47330(class_7706.java:2063)
        at de.guntram.mcmod.easiercrafting.RecipeBook.updateRecipes(RecipeBook.java:376)
        at de.guntram.mcmod.easiercrafting.RecipeBook.afterInitGui(RecipeBook.java:152)
```

The method I'm calling is the one that gets the creative inventory tab names;  they aren't normally initialized until you enter creative mode. Deep inside this (line 3 in the stack trace), essentialgui does some stuff with tooltips, and from the error message, it assumes some string is longer than 1 character which is actually isn't.

As lordrius doesn't open source his code, I have no idea what exactly he's doing here or how to fix it, and I guess I can't fix it from my side anyways. So you really need to talk to him.

**Comment by somnomania** [comment]
Okay cool, thank you for letting me know. I did have it happen in creative
mode, I forgot to mention that part.
